name: Build and Release Go Application

on:
    push:
        tags:
            - "v*.*.*"
            - "v*.*"

jobs:
    build:
        name: Build and Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.21 # Change this to your desired Go version

            - name: Set release details
              id: vars
              run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

            - name: Build for Linux
              run: GOOS=linux GOARCH=amd64 go build -o Username-Generator-linux

            - name: Build for Windows
              run: GOOS=windows GOARCH=amd64 go build -o Username-Generator-windows.exe

            - name: Build for macOS
              run: GOOS=darwin GOARCH=amd64 go build -o Username-Generator-macos

            - name: Archive Artifacts
              run: |
                  zip Username-Generator-${{ steps.vars.outputs.tag }}-linux.zip Username-Generator-linux
                  zip Username-Generator-${{ steps.vars.outputs.tag }}-windows.zip Username-Generator-windows.exe
                  zip Username-Generator-${{ steps.vars.outputs.tag }}-macos.zip Username-Generator-macos
            - name: Upload Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: Username-Generator
                  path: |
                      Username-Generator-${{ steps.vars.outputs.tag }}-linux.zip
                      Username-Generator-${{ steps.vars.outputs.tag }}-windows.zip
                      Username-Generator-${{ steps.vars.outputs.tag }}-macos.zip
    release:
        name: Create GitHub Release
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Download Artifacts
              uses: actions/download-artifact@v2
              with:
                  name: Username-Generator

            - name: Set release details
              id: vars
              run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

            - name: Set release type
              id: release_type
              run: if [[ "${{ steps.vars.outputs.tag }} =~ ^v[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then echo "preRelease=true" >> $GITHUB_OUTPUT else echo "preRelease=false" >> $GITHUB_OUTPUT fi

            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      Username-Generator-${{ steps.vars.outputs.tag }}-linux.zip
                      Username-Generator-${{ steps.vars.outputs.tag }}-windows.zip
                      Username-Generator-${{ steps.vars.outputs.tag }}-macos.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

            - name: Upload Release Notes
              run: echo ::set-output name=body::"Release Notes for ${{ steps.vars.outputs.tag }} - in the future there might be some more details here."
              id: release_notes

            - name: Publish Release
              uses: softprops/action-gh-release@v1
              with:
                  files: ${{ steps.create_release.outputs.files }}
                  tag_name: ${{ steps.vars.outputs.tag }}
                  name: Release ${{ steps.vars.outputs.tag }}
                  body: ${{ steps.release_notes.outputs.body }}
                  prerelease: ${{ steps.release_type.outputs.preRelease }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
